# The GitHub Actions docs (https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#on)
# describe other options for 'on', 'pull_request' is a good default.
on:
 push:
   branches:
   - main
   paths:
   - terraform/**
 pull_request:
   branches:
   - main
   paths:
   - terraform/**

jobs:
  terraform:
    name: "Terraform Infrastructure Change Management"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Setup JQ
        uses: sergeysova/jq-action@v2

      # Checkout the base branch of the pull request (e.g. main/master).
      - uses: clingclangclick/terraform-config-inspect-action@v0
      - name: Setup terraform-config-inspect-action
        run: | 
          ls -la 
          ls ~/go/bin
          mv terraform-config-inspect /usr/bin/terraform-config-inspect
          terraform-config-inspect terraform/prod --json | jq -r -c .module_calls[].source | while read i; do if [[ $i = @("git@github.com:cahcommercial/outcomes-aws-ct-tf-module-ec2") ]]; then echo "found module"; else echo "module not found" && exit 1; fi; done;