# The GitHub Actions docs (https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#on)
# describe other options for 'on', 'pull_request' is a good default.
on:
 push:
   branches:
   - main
   paths:
   - terraform/**
 pull_request:
   branches:
   - main
   paths:
   - terraform/**

jobs:
  terraform:
    name: "Terraform Infrastructure Change Management"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: checkout_repo
        uses: actions/checkout@v3
      - name: Setup Terraform with specified version on the runner
        uses: hashicorp/setup-terraform@v2
        with:
         terraform_version: 1.6.0
      - name: Setup JQ
        uses: dcarbone/install-jq-action@v2 
        with: 
          version: '1.7'
      # Checkout the base branch of the pull request (e.g. main/master).
      - name: Setup terraform-config-inspect-action
        uses: clingclangclick/terraform-config-inspect-action@v0
        id: tf-config-inspect
        with:
          path: terraform/prod
      - name: test output
        run: | 
          echo '${{ steps.tf-config-inspect.outputs.config }}' | jq -r -c .module_calls[].source test.json | while read i; do if [[ $i = @("git@github.com:cahcommercial/outcomes-aws-ct-tf-module-ec2") ]]; then echo "found module"; else echo "module not found" && exit 1; fi; done;
      
        