# The GitHub Actions docs (https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#on)
# describe other options for 'on', 'pull_request' is a good default.
on:
 push:
   branches:
   - main
   paths:
   - terraform/**
 pull_request:
   branches:
   - main
   paths:
   - terraform/**

jobs:
  terraform:
    name: "Terraform Infrastructure Change Management"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Setup JQ
        uses: sergeysova/jq-action@v2
      # Checkout the base branch of the pull request (e.g. main/master).
      - name: Setup terraform-config-inspect-action
        uses: clingclangclick/terraform-config-inspect-action@v0
        id: tf-config-inspect
        with:
          path: ${{ github.workspace }}/terraform/prod/
          # query: gojq -r -c .module_calls[].source
      - name: test output 
        run: echo "${{ steps.tf-config-inspect.outputs.config}}"
        